import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "@/style/main.scss";

const poppins = Poppins({
  weight: ["100", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        <div id="portal"></div>
      </body>
    </html>
  );
}
